version: "3.7"
services:
  keepnote:
    image: keepnote
    container_name: keepnote
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/keepnote/my_notes/:/home/keepnote/my_notes/
      - ~/.config/keepnote:/home/keepnote/.config/keepnote
    environment:
      - DISPLAY=unix$DISPLAY
    entrypoint: keepnote my_notes

